version: "3"

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db/:/root/db/
    environment:
      - SQLITE3_DB=db.sqlite3

  web:
    build: ./social_network
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./social_network:/code
    ports:
      - "8000:8000"
    depends_on:
      - sqlite3

